
trigger:
  branches:
    include:
      - master

pool:
  name: Ansys
steps:
- script: |
   echo "Current working directory is %CD%"
   python -m pip install -r requirements.txt
   echo "Python dependencies are installed"
  displayName: 'Install Python Dependencies'

- script: |
   echo Start packaging Python
   cd electron_ui
   pyinstaller.exe ..\downloader_backend.py --distpath python_build --workpath %TEMP% --exclude-module tkinter --onefile
  displayName: 'Build Python Exe'

- script: |
   cd electron_ui
   echo "Current working directory is %CD%"
   npm install
   echo "Dependencies are installed"
  displayName: 'Install Dependencies'

- script: |
   cd electron_ui
   npm run dist
  displayName: 'Build Electron'

- script: |
    python "upload_build_to_server.py" --channel="stable" --platform="windows_64"  --base-url="http://ottbld01:1337" --username="STATIC_USERNAME" --password="STATIC_PASSWORD" --path="%CD%\\electron_ui\\dist"
  displayName: 'Upload build to server'