
trigger:
  branches:
    include:
      - master
      - refs/tags/v*

pool:
  name: Ansys
steps:
- script: |
   echo Start packaging Python
   cd electron_ui
   pyinstaller.exe ..\downloader_backend.py --distpath python_build --workpath %TEMP% --exclude-module tkinter --onefile
  displayName: 'Build Python Exe'

- script: |
   cd electron_ui
   electron-packager  ./ --platform=win32 --arch=x64 --electron-version=8.2.3  --out=electron_build --overwrite --ignore="^.*\.py"  --ignore="__pycache__"
   npm run dist
  displayName: 'Build Electron'

- script: |
    for /f "delims=" %%i in ('git describe --tags') do set VERSION_TAG=%%i
    python "C:\GIT\upload.py" --channel="stable" --platform="windows_64"  --base-url="http://ottbld01:1337" --username="STATIC_USERNAME" --password="STATIC_PASSWORD" --path="%CD%\\dist"  --version="%VERSION_TAG:~1,50%"
  displayName: 'upload build to server'